version: '3.1'

services:

  db:
    image: postgres:13.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: esports
      POSTGRES_PASSWORD: passme
      POSTGRES_DB: esports

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080